### ISSUE TITLE
Reverse color mode doesn't work when using a light theme

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#759]
Downstream issue: https://github.com/Microsoft/vscode/issues/30024

JS has no knowledge of the background/foreground colors so it just uses `.xterm-bg-color-15` and `.xterm-color-0` for reversed unstyled text which should be the opposite on light themes.

**Comment by Tyriar** [comment]
Currently the default background/foreground is specified in the following CSS:

```css
#terminal-container .terminal {
    background-color: #111;
    color: #fafafa;
}
```

**Comment by wavebeem** [comment]
Related: reverse video + red foreground on a light theme gives black text on a red background, rather than white text on a red background:

![image](https://user-images.githubusercontent.com/176815/27941108-c4f46daa-6283-11e7-8bde-ad74eb926dc9.png)

**Comment by Tyriar** [comment]
Yep, that's the same root cause. reverse on defaults is always assumed it was default black bg and default white fg..

**Comment by wavebeem** [comment]
Cool, just figured I'd add that since I wasn't 100% sure if it would affect the issue or not.

**Comment by jerch** [comment]
Imho this can simply be solved by enforcing a default class settings identifiable by the emulator so the emulator can reverse those settings when needed, e.g. `fg-default` and `bg-default`. This would involve copying the settings over from fb to bg and vice versa for reversed.
Might be even easier to enforce default reversed classes in the theme settings, e.g. `fg-reversed` and `bg-reversed`. With those the theme creator is responsible to set those values to a reversed scheme.

**Comment by Tyriar** [comment]
Yes we used to reverse color as well in vscode and I really liked it. Unfortunately it's not the easiest thing to support using the new `SelectionManager`.

**Comment by Tyriar** [comment]
This was fixed with the renderer update.

**Comment by dcalhoun** [comment]
>This was fixed with the renderer update.

@Tyriar would you be able to elaborate on what commit/change was the fix? I'm still experiencing a similar issue that is outlined in facebook/jest#6494.

**Comment by Tyriar** [comment]
I commented on the issue
